---
- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Create defaults file
  template:
    src: alertmanager_opts.j2
    dest: /etc/default/alertmanager
    owner: root
    group: root
    mode: 0644
  register: _am_defaults

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ openio_alertmanager_config_dir }}"
    - "{{ openio_alertmanager_config_dir }}/templates"
    - "{{ openio_alertmanager_storage_path }}"

- name: Set alertmanager configuration
  template:
    src: "alertmanager.yml.j2"
    dest: "{{ openio_alertmanager_config_dir }}/alertmanager.yml"
    owner: root
    group: root
    # validate: "amtool check-config %s"
  tags: configure
  register: _am_conf

- name: Ensure alertmanager service is started and enabled
  systemd:
    daemon_reload: true
    name: alertmanager
    state: "{{ 'started' if openio_alertmanager_provision_only else 'restarted' }}"
    enabled: "{{ openio_alertmanager_service_enabled }}"
  when:
    - _am_defaults is changed or _am_conf is changed

- name: Check that service is up
  uri:
    url: "http://{{ openio_alertmanager_bind_address }}:{{ openio_alertmanager_bind_port }}"
    return_content: true
    status_code: 200
    register: _am_check
    retries: 3
    delay: 5
    until: _am_check is success
    changed_when: false
  when:
    - not openio_alertmanager_provision_only
...
