---
- include_role:
    name: openio-service
  vars:
    openio_service_type: "alertmanager"
    openio_service_namespace: "{{ openio_alertmanager_namespace }}"
    openio_service_maintenance_mode: "{{ openio_alertmanager_maintenance_mode }}"
    openio_service_directories:
      - path: "{{ openio_service_conf_dir }}/templates"
      - path: "{{ openio_service_volume }}"
    openio_service_packages:
      - oio-alertmanager
    openio_service_configuration_files:
      - name: alertmanager.yml
    openio_service_services:
      - command: >-
          /usr/sbin/oio-alertmanager
          --config.file={{ openio_service_conf_dir }}/alertmanager.yml
          --storage.path={{ openio_service_volume }}
          --web.listen-address={{ openio_alertmanager_bind_address }}:{{ openio_alertmanager_bind_port }}
        redirect_stdout_to_syslog: true
    openio_service_checks:
      - uri:
          url: "http://{{ openio_alertmanager_bind_address }}:{{ openio_alertmanager_bind_port }}/-/ready"
        retries: 10
        delay: 2
...
